FROM archlinux

ENV PATH $PATH:/root/.local/share/gem/ruby/3.0.0/bin

# Install dependencies
RUN pacman -Sy --noconfirm --needed archlinux-keyring
RUN pacman -Syu --noconfirm --needed git gcc make curl base-devel gdbm openssl libffi doxygen graphviz libyaml ttf-dejavu tk gdbm openssl libffi libyaml gmp zlib readline ruby

# Install fpm
RUN gem install --no-document fpm