on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}-env
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - mac
          - windows
          - arch
          - centos
          - debian
          - generic-linux
    steps:
      - uses: actions/checkout@v2

      - run: make ${{ matrix.target }}-env

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: github.ref_type != 'tag' || github.event_name == 'pull_request'
        run: make publish-${{ matrix.target }}-beta

      - if: github.ref_type == 'tag' || github.event_name != 'pull_request'
        run: |
          tag=$(echo ${{ github.ref }} | sed -E s:refs/[^/]+/::)
          if [ "$tag" = "" -o "$tag" = "main" ]; then
            tag=latest
          fi
          make tag=$tag publish-${{ matrix.target }}
